### ISSUE TITLE
Update version of Sphinx

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-metapackage#1400]
### Summary

We are currently building the docs build with Sphinx 3.3.0, which is very old at this point.  We should update the version of Sphinx to a more recent version, so the components can start using newer features of Sphinx and its extensions during their builds.

Component issues:

- [x] Qiskit/qiskit-terra#7469 (for Sphinx 4.4)
- [x] Qiskit/qiskit-terra#7534 (for Python 3.9)
- [x] Qiskit/qiskit-aer#1429 (for Python 3.9)
- [x] Qiskit/qiskit-experiments#612 (for Python 3.9)
- [x] Qiskit/qiskit-ignis#608 (for Python 3.9)

I am checking the component repositories manually, and all the ticked ones can build their documentation without error on Python 3.9 and Sphinx 4.4 on their current main branch:

- [x] Terra
- [x] Aer
- [x] Dynamics
- [x] Experiments
- [x] Finance
- [x] IBM Runtime
- [x] IBMQ Provider
- [x] Ignis
- [x] Machine Learning
- [x] Nature
- [x] Optimization
- [x] Tutorials (subject to Qiskit/qiskit-tutorials#1260, which will fix CI for _all_ Python versions)

**Comment by jakelishman** [comment]
Ok, we've now got all the necessary PRs merged, so we should be good to move the docs build up to a modern version of Sphinx.  I'll get on that.
