### ISSUE TITLE
Add alt-text to all images in Qiskit docs

### ISSUE THREAD

**Issue by lzdanski** [Qiskit/qiskit-metapackage#196]
Qiskit docs contain 53 images and 0 images are associated with alt text. 

**To-do**: Add alt-text to images in the following files.

```
..  image::
    :alt: alternate text
```

**Aer**

- [x] device_noise_simulation.rst (3)

- [x] simulate_experiments.rst (2)

- [x] simulate_statevectors.rst (2) 

**Qiskit**

- [x] getting-started.rst (6)

- [x] install.rst (2)

- [x] overview.rst (1)

**Ignis**

- [x] overview.rst (1)

**Terra**

- [x] plotting_data_in_qiskit.rst (14)

- [x] quantum_circuits.rst (12)

- [x] visualizing_a_quantum_circuit.rst (10)
